### ISSUE TITLE
求助大佬：启动机器人报错

### ISSUE THREAD

**Issue by manlongdan** [curtinlv/gd#1]
root@550fdc2698ca:/ql $ python3 -m jbot
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/ql/jbot/__init__.py", line 1, in <module>
    from telethon import TelegramClient, connection
ModuleNotFoundError: No module named 'telethon'

**Comment by 1260074755** [comment]
朋友，这个问题解决了吗

**Comment by manlongdan** [comment]
> 朋友，这个问题解决了吗

没有，业余选手

**Comment by achooyu** [comment]
我也是这样，删掉，重启，重新拉还是这样。有解决吗
