### ISSUE TITLE
 python3 -m jbot

### ISSUE THREAD

**Issue by liluosheng** [curtinlv/gd#53]
python3 -m jbot
出现这个错误

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/ql/jbot/__init__.py", line 90, in <module>
    jdbot = TelegramClient("bot", API_ID, API_HASH, connection=connectionType, proxy=proxy).start(bot_token=TOKEN)
  File "/usr/local/lib/python3.10/site-packages/telethon/client/auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/telethon/client/auth.py", line 140, in _start
    await self.connect()
  File "/usr/local/lib/python3.10/site-packages/telethon/client/telegrambaseclient.py", line 525, in connect
    if not await self._sender.connect(self._connection(
  File "/usr/local/lib/python3.10/site-packages/telethon/network/mtprotosender.py", line 127, in connect
    await self._connect()
  File "/usr/local/lib/python3.10/site-packages/telethon/network/mtprotosender.py", line 253, in _connect
    raise ConnectionError('Connection to Telegram failed {} time(s)'.format(self._retries))
ConnectionError: Connection to Telegram failed 5 time(s)

**Comment by chlchl1** [comment]
你好，解决这个问题没有了呢
