### ISSUE TITLE
启动的时候报这个错，这种错误影响吗？

### ISSUE THREAD

**Issue by nzmd** [curtinlv/gd#6]
![image](https://user-images.githubusercontent.com/21009810/160784255-539b475e-b64f-473c-a494-f9f9dd72732e.png)

**Comment by nzmd** [comment]
`2022-03-30 15:23:43,613 jbot INFO [load_module] 加载成功  cxjc_kill 
2022-03-30 15:23:43,707 asyncio ERROR [default_exception_handler] Task exception was never retrieved
future: <Task finished name='Task-18' coro=<hello() done, defined at /ql/jbot/__main__.py:71> exception=ValueError('Could not find the input entity for PeerUser(user_id=2146193033) (PeerUser). Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.')> 
Traceback (most recent call last):
  File "/ql/jbot/__main__.py", line 76, in hello
    await jdbot.send_message(chat_id, f'{str(hello_word)}\n\n\t{info}', link_preview=False)
  File "/usr/lib/python3.8/site-packages/telethon/client/messages.py", line 810, in send_message
    entity = await self.get_input_entity(entity)
  File "/usr/lib/python3.8/site-packages/telethon/client/users.py", line 466, in get_input_entity
    raise ValueError(
ValueError: Could not find the input entity for PeerUser(user_id=2146193033) (PeerUser). Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.`
